version: '3.5'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rails-web
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - /var/tmp
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
    # networks:
    #   - sample

  db:
    image: mysql:5.7
    container_name: rails-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    volumes:
      - ./tmp/db:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    # networks:
    #   - sample